# application.yml文件中添加如下配置：
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fowl_test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
