#port
server:
  port:8081
#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fowl_test?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.fowl.model.*

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
